CREATE TABLE users (
  id         INTEGER PRIMARY KEY,          -- GitHub user id (stable across renames)
  login      TEXT NOT NULL,                -- GitHub login, refreshed at every sign-in
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE workspaces (
  id         TEXT PRIMARY KEY,             -- random, generated by the server
  name       TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE workspace_members (
  workspace_id TEXT NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
  user_id      INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role         TEXT NOT NULL CHECK (role IN ('owner', 'editor', 'viewer')),
  PRIMARY KEY (workspace_id, user_id)
);
CREATE INDEX workspace_members_user ON workspace_members (user_id);

CREATE TABLE tokens (
  id           TEXT PRIMARY KEY,           -- public handle, used to list and revoke
  hash         TEXT NOT NULL UNIQUE,       -- SHA-256 of the secret, in hex
  user_id      INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  workspace_id TEXT REFERENCES workspaces (id) ON DELETE CASCADE,
                                           -- NULL: every workspace of the user
  name         TEXT NOT NULL,
  expires_at   INTEGER,                    -- NULL: no expiry
  created_at   INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX tokens_user ON tokens (user_id);

CREATE TABLE nodes (
  workspace_id TEXT NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
  id           TEXT NOT NULL,              -- node id, unique per workspace
  kind         TEXT NOT NULL CHECK (kind IN ('task', 'milestone')),
  title        TEXT NOT NULL,
  status       TEXT NOT NULL CHECK (status IN ('todo', 'doing', 'done', 'dropped')),
  due          TEXT,                       -- 'YYYY-MM-DD', or NULL
  tags         TEXT NOT NULL,              -- JSON array of strings
  depends_on   TEXT NOT NULL,              -- JSON array of node ids
  milestones   TEXT NOT NULL,              -- JSON array of node ids
  body         TEXT NOT NULL,              -- Markdown notes
  PRIMARY KEY (workspace_id, id)
);

CREATE TABLE changes (
  workspace_id    TEXT NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
  version         INTEGER NOT NULL,        -- 1, 2, 3, ... per workspace
  user_id         INTEGER NOT NULL REFERENCES users (id),
  token_id        TEXT NOT NULL,           -- tokens.id that made the write; kept after revocation
  token_name      TEXT NOT NULL,           -- tokens.name at the time
  agent           TEXT,                    -- the request's Topo-Agent header
  idempotency_key TEXT NOT NULL,
  ops             TEXT NOT NULL,           -- JSON array of operations, ids resolved
  created         TEXT NOT NULL,           -- JSON object: ref -> created node id
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY (workspace_id, version),
  UNIQUE (workspace_id, idempotency_key)
);
